// Generated code, don't edit

static GPIO::PinDef pins[GPIO::MaxPins] = {
	{ 12, MYNAME(GPIO::Led1), GPIO::PinModeOutput, 0, 0 }, // 0
	{ 13, MYNAME(GPIO::Led2), GPIO::PinModeOutput, 0, 0 }, // 1
	{ 14, MYNAME(GPIO::Led3), GPIO::PinModeOutput, 0, 0 }, // 2
	{ 15, MYNAME(GPIO::Led4), GPIO::PinModeOutput, 0, 0 }, // 3
	{ 41, MYNAME(GPIO::IsBrakeOn), GPIO::PinModeInput, 0, 0 }, // 4
	{ 47, MYNAME(GPIO::IsSignalLeft), GPIO::PinModeInput, 0, 0 }, // 5
	{ 49, MYNAME(GPIO::IsSignalRight), GPIO::PinModeInput, 0, 0 }, // 6
	{ 32, MYNAME(GPIO::IsParkingOn), GPIO::PinModeInput, 0, 0 }, // 7
	{ 40, MYNAME(GPIO::IsLoBeamOn), GPIO::PinModeInput, 0, 0 }, // 8
	{ 0, MYNAME(GPIO::IsHiBeamOn), GPIO::PinModeInput, 0, 0 }, // 9
	{ 44, MYNAME(GPIO::IsKeyAcc), GPIO::PinModeInput, 0, 0 }, // 10
	{ 46, MYNAME(GPIO::IsKeyOn), GPIO::PinModeInput, 0, 0 }, // 11
	{ 48, MYNAME(GPIO::IsCranking), GPIO::PinModeInput, 0, 0 }, // 12
	{ 43, MYNAME(GPIO::IsClimateOn), GPIO::PinModeInput, 0, 0 }, // 13
	{ 45, MYNAME(GPIO::IsHornOn), GPIO::PinModeInput, 0, 0 }, // 14
	{ 37, MYNAME(GPIO::IsTransNeutral), GPIO::PinModeInput, 0, 0 }, // 15
	{ 39, MYNAME(GPIO::IsTransReverse), GPIO::PinModeInput, 0, 0 }, // 16
	{ 0, MYNAME(GPIO::IsHazardsOn), GPIO::PinModeInput, 0, 0 }, // 17
	{ 0, MYNAME(GPIO::IsInteriorOn), GPIO::PinModeInput, 0, 0 }, // 18
	{ 0, MYNAME(GPIO::IsClusterBright), GPIO::PinModeInput, 0, 0 }, // 19
	{ 0, MYNAME(GPIO::IsFanSwitch1), GPIO::PinModeInput, 0, 0 }, // 20
	{ 0, MYNAME(GPIO::IsFanSwitch2), GPIO::PinModeInput, 0, 0 }, // 21
	{ 0, MYNAME(GPIO::IsMenuButton1), GPIO::PinModeInput, 0, 0 }, // 22
	{ 9, MYNAME(GPIO::IsMenuButton2), GPIO::PinModeInput, 0, 0 }, // 23
	{ 0, MYNAME(GPIO::RelayWipers), GPIO::PinModeOutput, 0, 0 }, // 24
	{ 0, MYNAME(GPIO::RelayClimate), GPIO::PinModeOutput, 0, 0 }, // 25
	{ 0, MYNAME(GPIO::RelayStarter), GPIO::PinModeOutput, 0, 0 }, // 26
	{ 0, MYNAME(GPIO::RelayHorn), GPIO::PinModeOutput, 0, 0 }, // 27
	{ 0, MYNAME(GPIO::RelayHiBeam), GPIO::PinModeOutput, 0, 0 }, // 28
	{ 31, MYNAME(GPIO::RelayLoBeam), GPIO::PinModeOutput, 0, 0 }, // 29
	{ 27, MYNAME(GPIO::RelaySignalLeft), GPIO::PinModeOutput, 0, 0 }, // 30
	{ 25, MYNAME(GPIO::RelaySignalRight), GPIO::PinModeOutput, 0, 0 }, // 31
	{ 23, MYNAME(GPIO::RelayParkingLeft), GPIO::PinModeOutput, 0, 0 }, // 32
	{ 0, MYNAME(GPIO::RelayParkingRight), GPIO::PinModeOutput, 0, 0 }, // 33
	{ 29, MYNAME(GPIO::RelayReverseLights), GPIO::PinModeOutput, 0, 0 }, // 34
	{ 33, MYNAME(GPIO::RelayBrakeLightLeft), GPIO::PinModeOutput, 0, 0 }, // 35
	{ 35, MYNAME(GPIO::RelayBrakeLightRight), GPIO::PinModeOutput, 0, 0 }, // 36
	{ 0, MYNAME(GPIO::RelayBrakeSignalLeft), GPIO::PinModeOutput, 0, 0 }, // 37
	{ 0, MYNAME(GPIO::RelayBrakeSignalRight), GPIO::PinModeOutput, 0, 0 }, // 38
	{ 0, MYNAME(GPIO::RelayFan1), GPIO::PinModeOutput|GPIO::PinModePWM, 0, 0 }, // 39
	{ 0, MYNAME(GPIO::RelayFan2), GPIO::PinModeOutput|GPIO::PinModePWM, 0, 0 }, // 40
	{ 0, MYNAME(GPIO::EPAS1), GPIO::PinModeOutput|GPIO::PinModePWM, 0, 0 }, // 41
	{ 0, MYNAME(GPIO::EPAS2), GPIO::PinModeOutput|GPIO::PinModePWM, 0, 0 }, // 42
	{ 0, MYNAME(GPIO::Gauge1), GPIO::PinModeOutput|GPIO::PinModePWM, 0, 0 }, // 43
	{ 0, MYNAME(GPIO::Gauge2), GPIO::PinModeOutput|GPIO::PinModePWM, 0, 0 }, // 44
	{ 0, MYNAME(GPIO::RadiatorTemp), GPIO::PinModeAnalog, 0, 0 }, // 45
	{ 0, MYNAME(GPIO::Fuel), GPIO::PinModeAnalog, 0, 0 }, // 46
	{ 0, MYNAME(GPIO::AMPS1), GPIO::PinModeAnalog, 0, 0 }, // 47
	{ 0, MYNAME(GPIO::HEGO1), GPIO::PinModeAnalog, 0, 0 }, // 48
	{ 0, MYNAME(GPIO::HEGO2), GPIO::PinModeAnalog, 0, 0 }, // 49
	{ 0, MYNAME(GPIO::BAR), GPIO::PinModeAnalog, 0, 0 }, // 50
	{ 0, MYNAME(GPIO::EGR), GPIO::PinModeAnalog, 0, 0 }, // 51
	{ 0, MYNAME(GPIO::VCC), GPIO::PinModeAnalog, 0, 0 }, // 52
	{ 0, MYNAME(GPIO::DEC), GPIO::PinModeAnalog, 0, 0 }, // 53
	{ 0, MYNAME(GPIO::TPS), GPIO::PinModeAnalog, 0, 0 }, // 54
	{ 0, MYNAME(GPIO::VSS), GPIO::PinModeInput|GPIO::PinModeEdge, 0, 0 }, // 55
	{ 0, MYNAME(GPIO::ECT), GPIO::PinModeAnalog, 0, 0 }, // 56
	{ 0, MYNAME(GPIO::MAF), GPIO::PinModeAnalog, 0, 0 }, // 57
	{ 0, MYNAME(GPIO::ACT), GPIO::PinModeAnalog, 0, 0 }, // 58
	{ 0, MYNAME(GPIO::Injector1), GPIO::PinModeOutput, 0, 0 }, // 59
	{ 0, MYNAME(GPIO::Injector2), GPIO::PinModeOutput, 0, 0 }, // 60
	{ 0, MYNAME(GPIO::Injector3), GPIO::PinModeOutput, 0, 0 }, // 61
	{ 0, MYNAME(GPIO::Injector4), GPIO::PinModeOutput, 0, 0 }, // 62
	{ 0, MYNAME(GPIO::Injector5), GPIO::PinModeOutput, 0, 0 }, // 63
	{ 0, MYNAME(GPIO::Injector6), GPIO::PinModeOutput, 0, 0 }, // 64
	{ 0, MYNAME(GPIO::Injector7), GPIO::PinModeOutput, 0, 0 }, // 65
	{ 0, MYNAME(GPIO::Injector8), GPIO::PinModeOutput, 0, 0 }, // 66
	{ 0, MYNAME(GPIO::Spark1), GPIO::PinModeOutput, 0, 0 }, // 67
	{ 0, MYNAME(GPIO::Spark2), GPIO::PinModeOutput, 0, 0 }, // 68
	{ 0, MYNAME(GPIO::Spark3), GPIO::PinModeOutput, 0, 0 }, // 69
	{ 0, MYNAME(GPIO::Spark4), GPIO::PinModeOutput, 0, 0 }, // 70
	{ 0, MYNAME(GPIO::Spark5), GPIO::PinModeOutput, 0, 0 }, // 71
	{ 0, MYNAME(GPIO::Spark6), GPIO::PinModeOutput, 0, 0 }, // 72
	{ 0, MYNAME(GPIO::Spark7), GPIO::PinModeOutput, 0, 0 }, // 73
	{ 0, MYNAME(GPIO::Spark8), GPIO::PinModeOutput, 0, 0 }, // 74
};

