// Generated code, don't edit

static GPIO::PinDef pins[MaxPins] = {
	{ 0, MYNAME(Injector1), PinModeOutput, 0, 0 }, // 0
	{ 0, MYNAME(Injector2), PinModeOutput, 0, 0 }, // 1
	{ 0, MYNAME(Injector3), PinModeOutput, 0, 0 }, // 2
	{ 0, MYNAME(Injector4), PinModeOutput, 0, 0 }, // 3
	{ 0, MYNAME(Injector5), PinModeOutput, 0, 0 }, // 4
	{ 0, MYNAME(Injector6), PinModeOutput, 0, 0 }, // 5
	{ 0, MYNAME(Injector7), PinModeOutput, 0, 0 }, // 6
	{ 0, MYNAME(Injector8), PinModeOutput, 0, 0 }, // 7
	{ 0, MYNAME(Spark1), PinModeOutput, 0, 0 }, // 8
	{ 0, MYNAME(Spark2), PinModeOutput, 0, 0 }, // 9
	{ 0, MYNAME(Spark3), PinModeOutput, 0, 0 }, // 10
	{ 0, MYNAME(Spark4), PinModeOutput, 0, 0 }, // 11
	{ 0, MYNAME(Spark5), PinModeOutput, 0, 0 }, // 12
	{ 0, MYNAME(Spark6), PinModeOutput, 0, 0 }, // 13
	{ 0, MYNAME(Spark7), PinModeOutput, 0, 0 }, // 14
	{ 0, MYNAME(Spark8), PinModeOutput, 0, 0 }, // 15
	{ 12, MYNAME(Led1), PinModeOutput, 0, 0 }, // 16
	{ 13, MYNAME(Led2), PinModeOutput, 0, 0 }, // 17
	{ 14, MYNAME(Led3), PinModeOutput, 0, 0 }, // 18
	{ 15, MYNAME(Led4), PinModeOutput, 0, 0 }, // 19
	{ 41, MYNAME(IsBrakeOn), PinModeInput, 0, 0 }, // 20
	{ 47, MYNAME(IsSignalLeft), PinModeInput, 0, 0 }, // 21
	{ 49, MYNAME(IsSignalRight), PinModeInput, 0, 0 }, // 22
	{ 32, MYNAME(IsParkingOn), PinModeInput, 0, 0 }, // 23
	{ 40, MYNAME(IsLoBeamOn), PinModeInput, 0, 0 }, // 24
	{ 0, MYNAME(IsHiBeamOn), PinModeInput, 0, 0 }, // 25
	{ 44, MYNAME(IsKeyAcc), PinModeInput, 0, 0 }, // 26
	{ 46, MYNAME(IsKeyOn), PinModeInput, 0, 0 }, // 27
	{ 48, MYNAME(IsCranking), PinModeInput, 0, 0 }, // 28
	{ 43, MYNAME(IsClimateOn), PinModeInput, 0, 0 }, // 29
	{ 45, MYNAME(IsHornOn), PinModeInput, 0, 0 }, // 30
	{ 37, MYNAME(IsTransNeutral), PinModeInput, 0, 0 }, // 31
	{ 39, MYNAME(IsTransReverse), PinModeInput, 0, 0 }, // 32
	{ 0, MYNAME(IsHazardsOn), PinModeInput, 0, 0 }, // 33
	{ 0, MYNAME(IsInteriorOn), PinModeInput, 0, 0 }, // 34
	{ 0, MYNAME(IsClusterBright), PinModeInput, 0, 0 }, // 35
	{ 0, MYNAME(IsFanSwitch1), PinModeInput, 0, 0 }, // 36
	{ 0, MYNAME(IsFanSwitch2), PinModeInput, 0, 0 }, // 37
	{ 0, MYNAME(IsMenuButton1), PinModeInput, 0, 0 }, // 38
	{ 9, MYNAME(IsMenuButton2), PinModeInput, 0, 0 }, // 39
	{ 0, MYNAME(RelayWipers), PinModeOutput, 0, 0 }, // 40
	{ 0, MYNAME(RelayClimate), PinModeOutput, 0, 0 }, // 41
	{ 0, MYNAME(RelayStarter), PinModeOutput, 0, 0 }, // 42
	{ 0, MYNAME(RelayHorn), PinModeOutput, 0, 0 }, // 43
	{ 0, MYNAME(RelayHiBeam), PinModeOutput, 0, 0 }, // 44
	{ 31, MYNAME(RelayLoBeam), PinModeOutput, 0, 0 }, // 45
	{ 27, MYNAME(RelaySignalLeft), PinModeOutput, 0, 0 }, // 46
	{ 25, MYNAME(RelaySignalRight), PinModeOutput, 0, 0 }, // 47
	{ 23, MYNAME(RelayParkingLeft), PinModeOutput, 0, 0 }, // 48
	{ 0, MYNAME(RelayParkingRight), PinModeOutput, 0, 0 }, // 49
	{ 29, MYNAME(RelayReverseLights), PinModeOutput, 0, 0 }, // 50
	{ 33, MYNAME(RelayBrakeLightLeft), PinModeOutput, 0, 0 }, // 51
	{ 35, MYNAME(RelayBrakeLightRight), PinModeOutput, 0, 0 }, // 52
	{ 0, MYNAME(RelayBrakeSignalLeft), PinModeOutput, 0, 0 }, // 53
	{ 0, MYNAME(RelayBrakeSignalRight), PinModeOutput, 0, 0 }, // 54
	{ 0, MYNAME(RelayFan1), PinModeOutput|PinModePWM, 0, 0 }, // 55
	{ 0, MYNAME(RelayFan2), PinModeOutput|PinModePWM, 0, 0 }, // 56
	{ 0, MYNAME(RelayEPAS1), PinModeOutput|PinModePWM, 0, 0 }, // 57
	{ 0, MYNAME(RelayEPAS2), PinModeOutput|PinModePWM, 0, 0 }, // 58
	{ 0, MYNAME(RelayGauge1), PinModeOutput|PinModePWM, 0, 0 }, // 59
	{ 0, MYNAME(RelayGauge2), PinModeOutput|PinModePWM, 0, 0 }, // 60
	{ 0, MYNAME(AnalogRadiatorTemp), PinModeAnalog, 0, 0 }, // 61
	{ 0, MYNAME(AnalogFuel), PinModeAnalog, 0, 0 }, // 62
	{ 0, MYNAME(AnalogAMPS1), PinModeAnalog, 0, 0 }, // 63
	{ 0, MYNAME(AnalogHEGO1), PinModeAnalog, 0, 0 }, // 64
	{ 0, MYNAME(AnalogHEGO2), PinModeAnalog, 0, 0 }, // 65
	{ 0, MYNAME(AnalogBAR), PinModeAnalog, 0, 0 }, // 66
	{ 0, MYNAME(AnalogEGR), PinModeAnalog, 0, 0 }, // 67
	{ 0, MYNAME(AnalogVCC), PinModeAnalog, 0, 0 }, // 68
	{ 0, MYNAME(AnalogDEC), PinModeAnalog, 0, 0 }, // 69
	{ 0, MYNAME(AnalogTPS), PinModeAnalog, 0, 0 }, // 70
	{ 0, MYNAME(AnalogVSS), PinModeInput|PinModeEdge, 0, 0 }, // 71
	{ 0, MYNAME(AnalogECT), PinModeAnalog, 0, 0 }, // 72
	{ 0, MYNAME(AnalogMAF), PinModeAnalog, 0, 0 }, // 73
	{ 0, MYNAME(AnalogACT), PinModeAnalog, 0, 0 }, // 74
};

