// Generated code, don't edit

typedef enum {
	SensorIsKeyOn, // 0 - bit
	SensorIsCranking, // 1 - bit
	SensorDEC, // 2 - rpm
	SensorTPS, // 3 - deg
	SensorMAF, // 4 - v
	SensorVSS, // 5 - mph
	SensorACT, // 6 - f
	SensorECT, // 7 - f
	SensorHEGO1, // 8 - lamda
	SensorHEGO2, // 9 - lamda
	SensorBAR, // 10 - bp
	SensorEGR, // 11 - v
	SensorRPM, // 12 - rpm
	SensorAMPS1, // 13 - f
	SensorVCC, // 14 - v
	SensorGEAR, // 15 - scalar
	VehicleFuelSender, // 16 - pct
	VehicleRadiatorTemp, // 17 - deg
	VehicleGauge1, // 18 - pct
	VehicleGauge2, // 19 - deg
	CalcFuelPump, // 20 - pwm
	CalcFan1, // 21 - pwm
	CalcFan2, // 22 - pwm
	CalcEPAS1, // 23 - pwm
	CalcEPAS2, // 24 - pwm
	CalcFinalPulseAdvance, // 25 - deg
	CalcFinalSparkAdvance, // 26 - deg
	CalcFinalPulseWidth, // 27 - us
	CalcFinalSparkWidth, // 28 - us
	CalcFinalLamda, // 29 - lamda
	CalcLoad, // 30 - pct
	CalcVolumetricRate, // 31 - lb/hr
	CalcTheoreticalRate, // 32 - lb/hr
	CalcDisplacementVolume, // 33 - cf/min
	CalcLbsPerHr, // 34 - lb/hr
	CalcGalPerHour, // 35 - gal/hr
	CalcMPG, // 36 - mpg
	CalcDutyCycle, // 37 - pct
	CalcThrottleRate, // 38 - deg/s
	CalcRPMtoMPH, // 39 - mph
	FlagIsWOT, // 40 - bit
	FlagIsLimpMode, // 41 - bit
	FlagIsClosedLoop, // 42 - bit
	FlagIsHighAlt, // 43 - bit
	FlagIsMonitoring, // 44 - scalar
	TimeOnSeconds, // 45 - sec
	TimeCrankSeconds, // 46 - sec
	TimeRunSeconds, // 47 - sec
	TimeIdleSeconds, // 48 - sec
	TimeMovingSeconds, // 49 - sec
	TableAccelEnrichment, // 50 - lb/min
	TableFuelBase, // 51 - a/f
	TableFuelStartup, // 52 - a/f
	TableInjectorTiming, // 53 - deg
	TableSparkAltitude, // 54 - deg
	TableSparkBase, // 55 - deg
	TableSparkLimp, // 56 - deg
	FuncEecLoadScaling, // 57 - ratio
	FuncMafTransfer, // 58 - kg/hr
	FuncAcceleratorEnrichmentMultiplierVsTp, // 59 - ratio
	FuncOpenLoopFuelMultiplierVsAct, // 60 - ratio
	FuncMinLowSpeedDwell, // 61 - ms
	FuncMinHighSpeedDwell, // 62 - ms
	FuncMaximumDashpotClip, // 63 - lb/min
	FuncSeaLevelLuggingOLFuelMultiplier, // 64 - ratio
	FuncAltitudeLuggingOLFuelMultiplier, // 65 - ratio
	FuncInjectorOffsetVsBatteryVoltage, // 66 - v
	FuncOpenLoopFuelMultiplierVsRpm, // 67 - ratio
	FuncCrankFuelPulseWidthMultiplier, // 68 - ratio
	FuncCrankingFuelPulseWidthVsEct, // 69 - ms
	FuncSparkAdvanceVsAct, // 70 - deg
	FuncSparkAdvanceVsBp, // 71 - deg
	FuncSparkAdvanceRateVsRpm, // 72 - deg
	FuncWotFuelMultiplierVsRpm, // 73 - ratio
	FuncWotSparkAdvanceVsRpm, // 74 - deg
	FuncWotSparkAdvanceVsEct, // 75 - deg
	FuncWotSparkAdvanceVsAct, // 76 - deg
	FuncTransmissionRatio, // 77 - ratio
	ConstInjHiSlope, // 78 - ms
	ConstInjLoSlope, // 79 - ms
	ConstCylinders, // 80 - scalar
	ConstCoils, // 81 - scalar
	ConstEncoderTeeth, // 82 - scalar
	ConstEncoderRatio, // 83 - ratio
	ConstEncoderCompare, // 84 - scalar
	ConstEncoderSyncHigh, // 85 - bit
	ConstEncoderSyncShort, // 86 - bit
	ConstEncoderCountOffset, // 87 - scalar
	ConstEncoderDegreesOffset, // 88 - scalar
	ConstAxleRatio, // 89 - ratio
	ConstTireDiameter, // 90 - in
	ConstGallonWeight, // 91 - lbs
	ConstCrankingRPM, // 92 - rpm
	ConstIdleRPM, // 93 - rpm
	ConstMaxRPM, // 94 - rpm
	ConstStaticTiming, // 95 - deg
	ConstClosedLoopMinTemp, // 96 - f
	ConstHighAlt, // 97 - bp
	ConstWOT, // 98 - deg
	ConstLamda, // 99 - ratio
	ConstCamIntakeCenter, // 100 - deg
	ConstCamIntakeDuration, // 101 - deg
	ConstCamExhaustCenter, // 102 - deg
	ConstCamExhaustDuration, // 103 - deg
	ConstTicksInUS, // 104 - scalar
	ConstCuIn, // 105 - cuin
	MaxParam
} ParamTypeId;

static const uint16_t MaxEncoderTeeth = 62;
static const uint16_t MaxCylinders = 16;
static const uint16_t MaxCoils = 16;

