STDIR=~/dev/stm32/STM32Cube_FW_L0_V1.7.0

STINC=\
/Drivers/STM32L0xx_HAL_Driver/Src/ \
/Drivers/STM32L0xx_HAL_Driver/ \
/Drivers/BSP/STM32L0xx_Nucleo/ \
/Drivers/CMSIS/Include/ \
/Drivers/CMSIS/Device/ST/STM32L0xx/ \
/Drivers/CMSIS/Device/ST/STM32L0xx/Source/Templates/gcc/startup_stm32l053xx.s

CFLAGS = -T../stm32l152re_flash.ld
CFLAGS += -DSTM32L0 -DSTM32L053xx
CFLAGS += -mcpu=cortex-m0

include ../Makefile.st

SRCS += cube/startup_stm32l053xx.s
